spring:
  datasource:
    url: jdbc:mariadb://elg5164-order-db.cognfqvowvlv.us-east-2.rds.amazonaws.com:3306/mariadbtest?autoReconnect=true&useSSL=false
    username: admin
    password: admin4321
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  hikari:
    maximum-pool-size: 8
    minimum-idle: 1
    connection-timeout: 10000
    idle-timeout: 600000
    max-lifetime: 1800000

server:
    port: 8082

management:
  enable:
    process:
      cpu:
        usage: true

  endpoints:
    web:
      exposure:
        include: '*'

prometheus:
  metrics:
    export:
      enabled: true
